kind: pipeline
name: default
steps:
- name: publish-amd64
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: Docker/Dockerfile.amd64 
    tag: ${DRONE_TAG}-linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: luistt/drone-prime-publish
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    #- push
    - tag

- name: publish-arm64
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: Docker/Dockerfile.arm64 
    tag: ${DRONE_TAG}-linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: luistt/drone-prime-publish
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    #- push
    - tag

- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock