kind: pipeline
name: default
steps:
- name: publish-amd64
  image: plugins/docker
  environment:
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: Docker/Dockerfile.amd64 
    tag: ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: luistt/drone-prime-publish
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    #- push
    - tag

- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    target: luistt/drone-prime-publish:${DRONE_TAG}
    template: luistt/drone-prime-publish:${DRONE_TAG}-OS-ARCH
    platforms:
      - linux/amd64
      #- linux/arm
      #- linux/arm64V
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    #- push
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock